### PR TITLE
Generic RPC task added

### PR DESCRIPTION
**Pull request by maercu**
Added a "bare-bones" rpc call which does not apply any formatting/standardization beyond the outer most rpc tag.

### CODE REVIEW

**Comment by h4ndzdatm0ld** [comment]
Hey, thanks for the contrib. Would require all the linting/tests to pass and unit tests - Let me know if you need help

**Comment by maercu** [comment]
> Hey, thanks for the contrib. Would require all the linting/tests to pass and unit tests - Let me know if you need help

Hi. Yeah that was expected, was a quick shot PR. Let me check the acitons/pipeline and update the code. I will come back to you if I have any questions.

**Comment by maercu** [comment]
@h4ndzdatm0ld Do you need unit-tests for all platforms or is a single platform (for example IOSXE) suficent?

**Comment by h4ndzdatm0ld** [comment]
@maercu Unit tests don't require to talk to anything, so just make it generic as an example to a Cisco device. There are many examples in this repo. However,  integration tests use containerlab and you should make a simple interaction with the Arista box. Those tests run in the CI/CD of this project

**Comment by maercu** [comment]
Yeah, let me close this, fix it and create a new, clean PR.

**Pull request closed without merging**
