### PR TITLE
bare bone rpc task added

### PR DESCRIPTION
**Pull request by maercu**

### CODE REVIEW

**Comment by muffi-dn** [comment]
Wonderful, I just came here to raise an issue on adding a rpc task but you seem to have done a great job already. Thanks

Can I also request to also allow an etree element and not just string based payloads for this task, if you are not too keen I can add it in once the PR is merged.

**Comment by muffi-dn** [comment]
@h4ndzdatm0ld would it be possible to merge this ?

**Comment by h4ndzdatm0ld** [comment]
> @h4ndzdatm0ld would it be possible to merge this ?



> Wonderful, I just came here to raise an issue on adding a rpc task but you seem to have done a great job already. Thanks
> 
> Can I also request to also allow an etree element and not just string based payloads for this task, if you are not too keen I can add it in once the PR is merged.

Hey, thanks for checking in. Big thanks to @maercu - Lets get his code merged, and if you want to submit a subsequent PR to include such feature, please feel free! Ensure that you add proper unit and integration testing and test in your local environment. I will add a small bit of documentation on how to test locally, as we discovered that the docker-compose containerlab sometimes has issues, but if you run it outside of docker it's fine. tldr: run the `command` value of the clab service in the docker-compose file and then test against the arista box when integration testing, until further notice.

**Comment by muffi-dn** [comment]
> > @h4ndzdatm0ld would it be possible to merge this ?
> 
> > Wonderful, I just came here to raise an issue on adding a rpc task but you seem to have done a great job already. Thanks
> > Can I also request to also allow an etree element and not just string based payloads for this task, if you are not too keen I can add it in once the PR is merged.
> 
> Hey, thanks for checking in. Big thanks to @maercu - Lets get his code merged, and if you want to submit a subsequent PR to include such feature, please feel free! Ensure that you add proper unit and integration testing and test in your local environment. I will add a small bit of documentation on how to test locally, as we discovered that the docker-compose containerlab sometimes has issues, but if you run it outside of docker it's fine. tldr: run the `command` value of the clab service in the docker-compose file and then test against the arista box when integration testing, until further notice.

Perfect, thank you for the quick merge.

**Pull request merged**
